### ISSUE TITLE
Unable to login in the United States

### ISSUE THREAD

**Issue by yieldhog** [hasscc/petkit#1]
Hi -- awesome to see the work! I am based in the United States, per the app, I login with an email/password. I don't see any other username in the app. Putting email/password in the config doesn't seem to work. Any thoughts? Thanks for the work

**Comment by al-one** [comment]
This configuration variable `api_base` is `http://api.petkit.cn/6/​` by default, you can try to change it to `http://api.petkt.com/latest/`.

**Comment by yieldhog** [comment]
@al-one hm, that didn't seem to work. I tried using the account "Nickname" and also my email. Is there a way I can help debug?

**Comment by al-one** [comment]
Check any [logs](https://my.home-assistant.io/redirect/logs) about `petkit`.

**Comment by yieldhog** [comment]
Ah, it works! I realized that I had auto-corrected the url to petkit.com rather than petkt.com. Thanks so much!

**Comment by al-one** [comment]
So what is the correct `api_base` in the US ?

**Comment by yieldhog** [comment]
It's probably helpful to update your README for US configuration so people are aware, the following works for me. Thanks again!
```
petkit:
  # Single account
  username: email
  password: password
  api_base: http://api.petkt.com/latest/
```
